name: Build SmartWebView APK

on:
  push:
    branches:
      - main    # Change to 'master' if your default branch is master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK (Java Development Kit)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Make Gradle executable
      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      # Step 4: Build the APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Step 5: Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: SmartWebView-APK
          path: app/build/outputs/apk/debug/app-debug.apk
